// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProyectoFac.Context;

#nullable disable

namespace ProyectoFac.Migrations
{
    [DbContext(typeof(StoreContext))]
    partial class StoreContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ProyectoFac.Models.Cliente", b =>
                {
                    b.Property<int>("prg_int_idcliente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("prg_dt_fecharegistro")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("prg_int_tipo")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("prg_vch_direccion")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("prg_vch_email")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("prg_vch_nombre")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("prg_vch_rut")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("prg_vch_telefono")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("prg_int_idcliente");

                    b.ToTable("tbl_clientes");
                });

            modelBuilder.Entity("ProyectoFac.Models.ContratoFactoring", b =>
                {
                    b.Property<int>("prg_int_idcontrato")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<decimal>("prg_dec_montocedido")
                        .HasColumnType("decimal(12,2)");

                    b.Property<decimal>("prg_dec_tasainteres")
                        .HasColumnType("decimal(5,2)");

                    b.Property<DateTime>("prg_dt_fechacesion")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("prg_int_identidad")
                        .HasColumnType("int");

                    b.Property<int>("prg_int_idfactura")
                        .HasColumnType("int");

                    b.Property<int>("prg_int_plazodias")
                        .HasColumnType("int");

                    b.Property<string>("prg_vch_estado")
                        .IsRequired()
                        .HasColumnType("enum('activo','finalizado','cancelado')");

                    b.HasKey("prg_int_idcontrato");

                    b.ToTable("tbl_contratosFactoring");
                });

            modelBuilder.Entity("ProyectoFac.Models.EntidadFinanciera", b =>
                {
                    b.Property<int>("prg_int_identidad")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("prg_vch_direccion")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<string>("prg_vch_email")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("prg_vch_nombre")
                        .IsRequired()
                        .HasColumnType("varchar(150)");

                    b.Property<string>("prg_vch_ruc")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<string>("prg_vch_telefono")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.HasKey("prg_int_identidad");

                    b.ToTable("tbl_entidadesFinancieras");
                });

            modelBuilder.Entity("ProyectoFac.Models.Factura", b =>
                {
                    b.Property<int>("prg_int_idfactura")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<decimal>("prg_dec_monto")
                        .HasColumnType("decimal(12,2)");

                    b.Property<DateTime>("prg_dt_fechaemision")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("prg_dt_fechavencimiento")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("prg_int_idcliente")
                        .HasColumnType("int");

                    b.Property<string>("prg_txt_descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("prg_vch_estado")
                        .IsRequired()
                        .HasColumnType("enum('pendiente','cedida','pagada','vencida')");

                    b.Property<string>("prg_vch_moneda")
                        .IsRequired()
                        .HasColumnType("enum('PEN','USD','EUR')");

                    b.Property<string>("prg_vch_numerofactura")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.HasKey("prg_int_idfactura");

                    b.ToTable("tbl_facturas");
                });

            modelBuilder.Entity("ProyectoFac.Models.Garantia", b =>
                {
                    b.Property<int>("prg_int_idgarantia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<decimal?>("prg_dec_valorestimado")
                        .HasColumnType("decimal(12,2)");

                    b.Property<DateTime>("prg_dt_fecharegistro")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("prg_int_idcliente")
                        .HasColumnType("int");

                    b.Property<string>("prg_txt_descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("prg_vch_tipo")
                        .IsRequired()
                        .HasColumnType("enum('hipoteca','prenda','aval','fianza')");

                    b.HasKey("prg_int_idgarantia");

                    b.ToTable("tbl_garantias");
                });

            modelBuilder.Entity("ProyectoFac.Models.Movimiento", b =>
                {
                    b.Property<int>("prg_int_idmovimiento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("prg_dt_fecha")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("prg_int_idcontrato")
                        .HasColumnType("int");

                    b.Property<int?>("prg_int_idfactura")
                        .HasColumnType("int");

                    b.Property<int>("prg_int_idusuario")
                        .HasColumnType("int");

                    b.Property<string>("prg_txt_descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("prg_vch_accion")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.HasKey("prg_int_idmovimiento");

                    b.ToTable("tbl_movimientos");
                });

            modelBuilder.Entity("ProyectoFac.Models.Pago", b =>
                {
                    b.Property<int>("prg_int_idpago")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<decimal>("prg_dec_montopagado")
                        .HasColumnType("decimal(12,2)");

                    b.Property<DateTime>("prg_dt_fechapago")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("prg_int_idcontrato")
                        .HasColumnType("int");

                    b.Property<string>("prg_txt_observacion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("prg_vch_metodopago")
                        .IsRequired()
                        .HasColumnType("enum('transferencia','efectivo','cheque')");

                    b.HasKey("prg_int_idpago");

                    b.ToTable("tbl_pagos");
                });

            modelBuilder.Entity("ProyectoFac.Models.Usuario", b =>
                {
                    b.Property<int>("prg_int_idusuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("prg_dt_fechacreacion")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("prg_int_estado")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("prg_vch_clave")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("prg_vch_nombreusuario")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("prg_vch_rol")
                        .IsRequired()
                        .HasColumnType("enum('administrador','analista','cobranzas')");

                    b.HasKey("prg_int_idusuario");

                    b.ToTable("tbl_usuarios");
                });
#pragma warning restore 612, 618
        }
    }
}
